# Site settings
title: ricardoerl
description: > 
  Desarrollador web con un fuerte enfoque en diseño, rendimiento, escalabilidad y accesibilidad en aplicaciones y sitios web.
baseurl: "" 
url: "http://ricardoerl.com"
logo: "/assets/images/logo_circle_black_white-black.png"
github: "ricardoerl"
twitter: "ricardoerl"
instagram: "ricardoerl"
medium: "@ricardoerl"

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Sass settings
sass:
  sass_dir: css
  style: :compressed

# Build settings
exclude:
  - package.json
  - README.md
  - CNAME
  - node_modules

# Plugins
gems:
- jekyll-seo-tag
