# Site settings
title: ricardoerl.com
description: > 
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" 
url: "http://yourdomain.com"
github: "ricardoerl"
twitter: "ricardoerl"
instagram: "ricardoerl"
medium: "@ricardoerl"

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Sass settings
sass:
  sass_dir: assets/sass
  style: :compressed

# Build settings
exclude:
  - package.json
  - README.md
  - CNAME
  - node_modules
