# Site settings
title: ricardoerl.com
description: > 
  Desarrollador web con un fuerte enfoque en diseño, rendimiento, escalabilidad y experiencia de usuario en aplicaciones y sitios web.
baseurl: "" 
url: "http://ricardoerl.com"
github: "ricardoerl"
twitter: "ricardoerl"
instagram: "ricardoerl"
medium: "@ricardoerl"

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Sass settings
sass:
  sass_dir: assets/sass
  style: :compressed

# Build settings
exclude:
  - package.json
  - README.md
  - CNAME
  - node_modules
